### ISSUE TITLE
Hi there 👋

### ISSUE THREAD

**Issue by caoxiemeihao** [Carol42/Carol42#13]
**I've found your profile through:**

[readme-typing-svg](https://github.com/denvercoder1/readme-typing-svg)

**Message:**

Hi, nice to meet you! 😄  
I'm a from Hangzhou/China front-end developer 🧑‍💻  
This is the coolest I have ever seen README, I'm going to apply to my README 🎉  
I think if I found a BUG 🐛  

```diff
const Carol42 = {
-  pronouns: "she" | "her"
+  pronouns: "she" || "her"
}
```

**Comment by Carol42** [comment]
Hi @caoxiemeihao !!

Thanks for your feedback, I'm glad you like my profile readme 😄

And thanks for the bug notice, I'm going to fix it!

Have a nice day 😊
