### ISSUE TITLE
Your portfolio 

### ISSUE THREAD

**Issue by FarbodShabani** [Carol42/Carol42#23]
Your portfolio is not responsive for mobile phone and your codepen account link sent me to your git hub account 🤕

![Screenshot_2022-12-02-08-29-47-980_com.android.chrome.jpg](https://user-images.githubusercontent.com/61133134/205218255-a085ec7b-142f-407e-960c-151876175c33.jpg)

 - OS: [Android]
 - Browser [chrome]
 - Version [107.0.5304]

 - Device: [MIU]

Best of luck
Farbod Shabani

**Comment by Carol42** [comment]
Thanks for your feedback! I'm gonna fix this as soon as possible! :smile:

**Comment by FarbodShabani** [comment]
👍🌸
